spring:
  application:
    name: order-service
  datasource:
    url: <db_url> #jdbc:postgresql://localhost:5432/autoparts-online-shop
    username: <db_username> #postgres
    password: <db_password> #1
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: <eureka_server_url> #http://localhost:8761/eureka/
token:
  jwtSecret: <jwt_secret> #secret
  jwtIssuer: <jwt_issuer> #Artik&Egorik
  jwtLifetime: <jwt_lifetime> #1d
