spring:
  application:
    name: api-gateway


  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security-authentication-service
          uri: lb://security-authentication-service
          predicates:
            - Path=/api/v1/user/login
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: cart-service-route
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
server:
  port: 8080